version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: $IMAGE_BASE_PATH/main:latest
    environment:
      - DB_NAME=$DB_NAME
      - DEFAULT_CONVERSION_RATE=$DEFAULT_CONVERSION_RATE
      - JSON_KEY_FILE=$JSON_KEY_FILE
      - LOGURU_FORMAT=$LOGURU_FORMAT
      - SPREADSHEET_KEY=$SPREADSHEET_KEY
      - SQL_CLEAR_TABLE=$SQL_CLEAR_TABLE
      - SQL_CREATE_TABLE=$SQL_CREATE_TABLE
      - SQL_INSERT=$SQL_INSERT
      - TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - WORKSHEET_KEY=$WORKSHEET_KEY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
